# ============================================================================
# FILE: tenant_credentials.py
# PATH: backend/app/services/tenant_credentials.py
# PURPOSE: Super-Admin tenant credentials management. Creates operator tenants,
#          checks email availability, stores contact/contract/user metadata on
#          the tenant document, and supports admin password reset +
#          welcome-email dispatch.
#
#          Single-path user provisioning policy (2026-09-14): a new tenant is
#          created WITHOUT Auth users (POST /api/v1/admin/tenants). Users are
#          always created one at a time afterwards via
#          create_user_for_tenant (POST /api/v1/admin/users = Production Setup
#          Step 3). The legacy batch path (create_tenant_with_credentials) was
#          removed on 2026-09-17 (see PASSWORD_RESET_BUG_INVESTIGATION.md).
#
#          Security model (ICAO Doc 10159 data-intelligence principles):
#          - Passwords are generated by the platform, applied directly to
#            Firebase Auth, returned to the caller exactly once, and NEVER
#            persisted anywhere.
#          - Every action is written to the `audit_logs` collection.
#          - All callers must be SUPER_ADMIN (route dependency) and the setup
#            key is required for every mutation.
# AUTHOR: AviaSAFE Systems
# ============================================================================

import secrets
import string
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from firebase_admin import auth as fb_auth
from loguru import logger

from app.core.config import settings
from app.db import pg
from app.db.db_models import Tenant
from app.firebase import get_auth, get_db
from app.services import production_seed
from app.services.email_service import send_welcome_email
from app.services.users import upsert_user_doc, user_doc_from_auth_record

# ============================================================================
# Password generation
# ============================================================================

_ALPHABET = string.ascii_letters + string.digits + "!@#$%&*_-"


def generate_password(length: int = 14) -> str:
    """Cryptographically random password (>= 12 chars) with mixed char classes."""
    length = max(12, int(length or 14))
    pw = [
        secrets.choice(string.ascii_uppercase),
        secrets.choice(string.ascii_lowercase),
        secrets.choice(string.digits),
        secrets.choice("!@#$%&*_-"),
    ]
    pw += [secrets.choice(_ALPHABET) for _ in range(length - 4)]
    secrets.SystemRandom().shuffle(pw)
    return "".join(pw)


# ============================================================================
# Email availability
# ============================================================================

def check_email_available(email: str) -> Dict[str, Any]:
    """Return whether an email can be used for a new Auth account."""
    email = (email or "").strip().lower()
    if not email:
        raise ValueError("email is required")
    try:
        get_auth().get_user_by_email(email)
        return {"email": email, "available": False, "exists": True}
    except fb_auth.UserNotFoundError:
        return {"email": email, "available": True, "exists": False}


def _create_auth_user(auth, u: Dict[str, Any], tid: str) -> Dict[str, Any]:
    """Create one Auth user with role/tenant claims. Returns per-user result."""
    email = (u.get("email") or "").strip().lower()
    role = u.get("role") or "AIRLINE_ADMIN"
    password = u.get("password") or generate_password()
    full_name = (u.get("full_name") or "").strip()
    department = (u.get("department") or "").strip()
    try:
        user = auth.create_user(
            email=email,
            password=password,
            email_verified=True,
            display_name=full_name or None,
        )
        claims = {"role": role, "tenant_id": tid}
        if department:
            claims["department"] = department
        auth.update_user(user.uid, custom_claims=claims)
        doc = user_doc_from_auth_record(auth.get_user(user.uid))
        # Brand-new Auth user: the password was (re)set at creation time, so
        # stamp the freshness marker now instead of relying on a stale Auth
        # metadata field the Admin SDK does not expose.
        doc["password_updated_at"] = datetime.now(timezone.utc)
        upsert_user_doc(**doc)
        return {"email": email, "role": role, "uid": user.uid, "password": password, "status": "ok"}
    except fb_auth.EmailAlreadyExistsError:
        logger.warning(
            f"Email already exists in Firebase Auth, NOT re-creating or rotating "
            f"password: {email} (tenant={tid})"
        )
        return {"email": email, "role": role, "status": "error", "detail": "email already exists"}
    except Exception as e:
        logger.error(f"Failed to create Auth user {email}: {e}")
        return {"email": email, "role": role, "status": "error", "detail": str(e)}


# ============================================================================
# Single-user creation for an existing tenant
# ============================================================================

def create_user_for_tenant(data: Dict[str, Any], actor: Dict[str, Any]) -> Dict[str, Any]:
    """Create one tenant-scoped Auth user on an existing operator tenant.

    Applies the role/tenant/department claims to the Auth user, upserts the
    Firestore `users/{uid}` doc, appends the user record to the tenant's
    `users` list, best-effort dispatches a welcome email, and writes
    `USER_CREATED` + `USER_PASSWORD_SET` audit entries. The generated password
    is returned exactly once and never persisted. Raises `ValueError` when the
    tenant is missing, the email is already stored on the tenant, or the Auth
    creation fails (e.g. email already exists in Firebase Auth).
    """
    tid = (data.get("tenant_id") or "").strip()
    email = (data.get("email") or "").strip().lower()
    if not tid or not email:
        raise ValueError("tenant_id and email are required")

    # Duplicate check runs BEFORE Auth creation so a failed create never leaks
    # an orphan Auth user / PG row with an unsurfaced password.
    doc = _read_tenant(tid)  # raises ValueError when the tenant is missing
    users = list(doc.get("users") or [])
    if any((u.get("email") or "").strip().lower() == email for u in users):
        raise ValueError("email already exists on tenant")

    auth = get_auth()
    result = _create_auth_user(auth, {
        "email": email,
        "role": data.get("role") or "AIRLINE_ADMIN",
        "full_name": data.get("full_name") or "",
        "department": data.get("department") or "",
    }, tid)
    if result.get("status") != "ok":
        raise ValueError(result.get("detail") or "could not create user")

    now = datetime.now(timezone.utc)
    full_name = (data.get("full_name") or "").strip()
    department = (data.get("department") or "").strip()
    rec = {
        "email": result["email"],
        "role": result["role"],
        "uid": result.get("uid"),
        "full_name": full_name,
        "department": department,
        "status": "active",
        "created_at": now.isoformat(),
        "last_login": None,
    }

    users.append(rec)
    prev_audit = doc.get("audit") or {}
    _patch_tenant(tid, {
        "users": users,
        "audit": {
            "created_by": prev_audit.get("created_by"),
            "created_at": prev_audit.get("created_at"),
            "last_modified_by": actor.get("email") or actor.get("uid"),
            "last_modified_at": now.isoformat(),
        },
    })

    contact = doc.get("contact") or {}
    context = {
        "contact_name": full_name or contact.get("name") or "Safety Team",
        "tenant_name": doc.get("name") or tid,
        "admin_email": email,
        "password": result["password"],
        "login_url": settings.APP_LOGIN_URL,
        "support_email": settings.APP_SUPPORT_EMAIL,
    }
    try:
        delivery = send_welcome_email(email, context)
    except Exception as e:
        logger.warning(f"Welcome email for {email} failed: {e}")
        delivery = {"sent": False, "provider": "none", "to": email, "error": str(e)}

    production_seed._audit(
        "USER_CREATED", actor, tid,
        f"Created user {email} (role={result['role']}, dept={department or 'n/a'})",
        tenant_id=tid,
        metadata={"source": "route:admin.create_user_for_tenant", "target_uid": result.get("uid")},
    )
    production_seed._audit(
        "USER_PASSWORD_SET", actor, tid,
        f"Initial password set for {email} (uid={result.get('uid')})",
        tenant_id=tid,
        metadata={"source": "route:admin.create_user_for_tenant", "target_uid": result.get("uid")},
    )
    logger.info(f"User {email} created for tenant {tid} by {actor.get('uid')}")
    return {
        "tenant_id": tid,
        "email": result["email"],
        "uid": result.get("uid"),
        "role": result["role"],
        "password": result["password"],
        "delivery": delivery,
    }


# ============================================================================
# Credentials read / admin user resolution
# ============================================================================

def _read_tenant(tid: str) -> Dict[str, Any]:
    """Return the tenant row as a document; raise when missing."""
    data = pg.fetch_by(Tenant, "slug", tid)
    if data is None:
        raise ValueError(f"tenant not found: {tid}")
    data.pop("id", None)
    return data


def _patch_tenant(tid: str, patch: Dict[str, Any]) -> Dict[str, Any]:
    """Merge `patch` into the tenant (PG primary) with best-effort mirror."""
    existing = _read_tenant(tid)
    existing.update(patch)
    pg.upsert(Tenant, "slug", tid, existing)
    try:
        get_db().collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).set(dict(patch), merge=True)
    except Exception as e:  # pragma: no cover - mirror best effort
        logger.warning(f"Tenant mirror write failed ({tid}): {e}")
    return existing


def _admin_user_email(tenant_doc: Dict[str, Any], tid: str) -> str:
    for u in tenant_doc.get("users") or []:
        if u.get("role") == "AIRLINE_ADMIN" and u.get("email"):
            return u["email"]
    sm = tenant_doc.get("safety_manager") or {}
    if sm.get("email"):
        return sm["email"]
    raise ValueError(f"no admin user configured for tenant '{tid}'")


def get_tenant_credentials(tid: str) -> Dict[str, Any]:
    """Return the stored credential metadata for a tenant (no passwords)."""
    data = _read_tenant(tid)
    return {
        "tenant_id": tid,
        "name": data.get("name"),
        "status": data.get("status"),
        "contact": data.get("contact"),
        "contract": data.get("contract"),
        "users": data.get("users") or [],
        "audit": data.get("audit"),
        "regulator_id": data.get("regulator_id"),
        "country": data.get("country"),
    }


# ============================================================================
# Password reset + welcome email
# ============================================================================


def _refresh_password_mirror(uid: str) -> None:
    """Stamp ``password_updated_at`` = now on the PG users mirror row.

    Firebase Auth does not expose ``passwordUpdatedAt`` through the Admin SDK,
    so the freshness marker is captured at the moment we apply a new password
    and written to the PG ``users`` mirror. Never raises (best-effort; the
    original operation must not be blocked by the mirror write).
    """
    try:
        record = get_auth().get_user(uid)
        doc = user_doc_from_auth_record(record)
        doc["password_updated_at"] = datetime.now(timezone.utc)
        upsert_user_doc(**doc)
    except Exception as e:
        logger.warning(f"Failed to refresh PG password mirror for {uid}: {e}")


def reset_admin_password(tid: str, actor: Dict[str, Any]) -> Dict[str, Any]:
    """Reset the tenant's admin Auth password; returns it once."""
    data = _read_tenant(tid)
    email = _admin_user_email(data, tid)

    user = get_auth().get_user_by_email(email)
    password = generate_password()
    get_auth().update_user(user.uid, password=password)
    _refresh_password_mirror(user.uid)

    now = datetime.now(timezone.utc)
    _patch_tenant(tid, {"audit": {
        "created_by": (data.get("audit") or {}).get("created_by"),
        "created_at": (data.get("audit") or {}).get("created_at"),
        "last_modified_by": actor.get("email") or actor.get("uid"),
        "last_modified_at": now.isoformat(),
    }})
    production_seed._audit(
        "TENANT_PASSWORD_RESET", actor, tid,
        f"Reset admin password for {email} (uid={user.uid})",
        tenant_id=tid,
        metadata={"source": "route:admin.reset_admin_password", "target_uid": user.uid},
    )
    logger.info(f"Admin password reset for tenant {tid} by {actor.get('uid')}")
    return {"tenant_id": tid, "email": email, "password": password}


def send_welcome_email_for_tenant(tid: str, actor: Dict[str, Any]) -> Dict[str, Any]:
    """Set a fresh temporary password and email it to the tenant's admin."""
    data = _read_tenant(tid)
    email = _admin_user_email(data, tid)

    user = get_auth().get_user_by_email(email)
    password = generate_password()
    get_auth().update_user(user.uid, password=password)
    _refresh_password_mirror(user.uid)

    contact = data.get("contact") or {}
    context = {
        "contact_name": contact.get("name") or "there",
        "tenant_name": data.get("name") or tid,
        "admin_email": email,
        "password": password,
        "login_url": settings.APP_LOGIN_URL,
        "support_email": settings.APP_SUPPORT_EMAIL,
    }
    result = send_welcome_email(email, context)

    now = datetime.now(timezone.utc)
    _patch_tenant(tid, {"audit": {
        "created_by": (data.get("audit") or {}).get("created_by"),
        "created_at": (data.get("audit") or {}).get("created_at"),
        "last_modified_by": actor.get("email") or actor.get("uid"),
        "last_modified_at": now.isoformat(),
    }})
    production_seed._audit(
        "WELCOME_EMAIL_SENT", actor, tid,
        f"Welcome email to {email}: provider={result.get('provider')} sent={result.get('sent', False)}",
        tenant_id=tid,
        metadata={"source": "route:admin.send_welcome_email_for_tenant", "target_uid": user.uid},
    )
    logger.info(f"Welcome email for tenant {tid} -> {email} ({result.get('provider')})")
    return {
        "tenant_id": tid,
        "admin_email": email,
        "password": password,
        "delivery": result,
    }
