# ============================================================================
# FILE: tenant_credentials.py
# PATH: backend/app/services/tenant_credentials.py
# PURPOSE: Super-Admin tenant credentials management. Creates operator tenants
#          together with their Firebase Auth users, checks email availability,
#          stores contact/contract/user metadata on the tenant document, and
#          supports admin password reset + welcome-email dispatch.
#
#          Security model (ICAO Doc 10159 data-intelligence principles):
#          - Passwords are generated by the platform, applied directly to
#            Firebase Auth, returned to the caller exactly once, and NEVER
#            persisted anywhere.
#          - Every action is written to the `audit_logs` collection.
#          - All callers must be SUPER_ADMIN (route dependency) and the setup
#            key is required for every mutation.
# AUTHOR: AviaSAFE Systems
# ============================================================================

import secrets
import string
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from firebase_admin import auth as fb_auth
from loguru import logger

from app.core.config import settings
from app.firebase import get_auth, get_db
from app.services import production_seed
from app.services.email_service import send_welcome_email
from app.services.users import upsert_user_doc, user_doc_from_auth_record

# ============================================================================
# Password generation
# ============================================================================

_ALPHABET = string.ascii_letters + string.digits + "!@#$%&*_-"


def generate_password(length: int = 14) -> str:
    """Cryptographically random password (>= 12 chars) with mixed char classes."""
    length = max(12, int(length or 14))
    pw = [
        secrets.choice(string.ascii_uppercase),
        secrets.choice(string.ascii_lowercase),
        secrets.choice(string.digits),
        secrets.choice("!@#$%&*_-"),
    ]
    pw += [secrets.choice(_ALPHABET) for _ in range(length - 4)]
    secrets.SystemRandom().shuffle(pw)
    return "".join(pw)


# ============================================================================
# Email availability
# ============================================================================

def check_email_available(email: str) -> Dict[str, Any]:
    """Return whether an email can be used for a new Auth account."""
    email = (email or "").strip().lower()
    if not email:
        raise ValueError("email is required")
    try:
        get_auth().get_user_by_email(email)
        return {"email": email, "available": False, "exists": True}
    except fb_auth.UserNotFoundError:
        return {"email": email, "available": True, "exists": False}


# ============================================================================
# Tenant creation with credentials
# ============================================================================

def _stored_users(users: List[Dict[str, Any]], now: datetime) -> List[Dict[str, Any]]:
    out = []
    for u in users or []:
        email = (u.get("email") or "").strip().lower()
        if not email:
            continue
        out.append({
            "email": email,
            "role": u.get("role") or "AIRLINE_ADMIN",
            "full_name": (u.get("full_name") or "").strip(),
            "department": (u.get("department") or "").strip(),
            "status": "active",
            "created_at": now.isoformat(),
            "last_login": None,
        })
    return out


def _create_auth_user(auth, u: Dict[str, Any], tid: str) -> Dict[str, Any]:
    """Create one Auth user with role/tenant claims. Returns per-user result."""
    email = (u.get("email") or "").strip().lower()
    role = u.get("role") or "AIRLINE_ADMIN"
    password = u.get("password") or generate_password()
    full_name = (u.get("full_name") or "").strip()
    department = (u.get("department") or "").strip()
    try:
        user = auth.create_user(
            email=email,
            password=password,
            email_verified=True,
            display_name=full_name or None,
        )
        claims = {"role": role, "tenant_id": tid}
        if department:
            claims["department"] = department
        auth.update_user(user.uid, custom_claims=claims)
        upsert_user_doc(user.uid, user_doc_from_auth_record(auth.get_user(user.uid)))
        return {"email": email, "role": role, "uid": user.uid, "password": password, "status": "ok"}
    except fb_auth.EmailAlreadyExistsError:
        return {"email": email, "role": role, "status": "error", "detail": "email already exists"}
    except Exception as e:
        logger.error(f"Failed to create Auth user {email}: {e}")
        return {"email": email, "role": role, "status": "error", "detail": str(e)}


def create_tenant_with_credentials(data: Dict[str, Any], actor: Dict[str, Any]) -> Dict[str, Any]:
    """Create the tenant doc + Auth users; returns tenant + per-user results.

    The generated passwords appear in the response exactly once and are never
    stored. The tenant document stores contact/contract/user metadata only.
    """
    tid = data.get("tenant_id") or data.get("id")
    users = data.get("users") or []
    if not users:
        raise ValueError("users are required to create a tenant with credentials")

    doc = production_seed.create_tenant(data, actor)

    now = datetime.now(timezone.utc)
    db = get_db()

    auth = get_auth()
    user_results = [_create_auth_user(auth, u, tid) for u in users]

    by_email = {(u.get("email") or "").strip().lower(): u for u in users}
    stored_users = []
    for r in user_results:
        if r.get("status") != "ok":
            continue
        src = by_email.get(r["email"]) or {}
        stored_users.append({
            "email": r["email"],
            "role": r["role"],
            "uid": r.get("uid"),
            "full_name": (src.get("full_name") or "").strip(),
            "department": (src.get("department") or "").strip(),
            "status": "active",
            "created_at": now.isoformat(),
            "last_login": None,
        })

    update = {
        "status": data.get("status") or "active",
        "audit": {
            "created_by": actor.get("email") or actor.get("uid"),
            "created_at": now.isoformat(),
            "last_modified_by": None,
            "last_modified_at": None,
        },
    }
    if data.get("contact") is not None:
        update["contact"] = data["contact"]
    if data.get("contract") is not None:
        update["contract"] = data["contract"]
    if stored_users:
        update["users"] = stored_users
        admin = next((u for u in stored_users if u.get("role") == "AIRLINE_ADMIN"), stored_users[0])
        if not data.get("safety_manager"):
            update["safety_manager"] = {
                "email": admin["email"],
                "name": admin.get("full_name") or "",
                "uid": admin.get("uid"),
            }

    db.collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).set(update, merge=True)

    ok = sum(1 for r in user_results if r.get("status") == "ok")
    production_seed._audit(
        "TENANT_CREDENTIALS_CREATED", actor, tid,
        f"Created tenant '{doc['name']}' with {ok}/{len(user_results)} users",
    )
    logger.info(f"Tenant {tid} with credentials created by {actor.get('uid')}: {ok}/{len(user_results)} users")

    return {"tenant": doc, "users": user_results}


# ============================================================================
# Credentials read / admin user resolution
# ============================================================================

def _admin_user_email(tenant_doc: Dict[str, Any], tid: str) -> str:
    for u in tenant_doc.get("users") or []:
        if u.get("role") == "AIRLINE_ADMIN" and u.get("email"):
            return u["email"]
    sm = tenant_doc.get("safety_manager") or {}
    if sm.get("email"):
        return sm["email"]
    raise ValueError(f"no admin user configured for tenant '{tid}'")


def get_tenant_credentials(tid: str) -> Dict[str, Any]:
    """Return the stored credential metadata for a tenant (no passwords)."""
    doc = get_db().collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).get()
    if not doc.exists:
        raise ValueError(f"tenant not found: {tid}")
    data = dict(doc.to_dict() or {})
    data["id"] = tid
    return {
        "tenant_id": tid,
        "name": data.get("name"),
        "status": data.get("status"),
        "contact": data.get("contact"),
        "contract": data.get("contract"),
        "users": data.get("users") or [],
        "audit": data.get("audit"),
        "regulator_id": data.get("regulator_id"),
        "country": data.get("country"),
    }


# ============================================================================
# Password reset + welcome email
# ============================================================================

def reset_admin_password(tid: str, actor: Dict[str, Any]) -> Dict[str, Any]:
    """Reset the tenant's admin Auth password; returns it once."""
    doc = get_db().collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).get()
    if not doc.exists:
        raise ValueError(f"tenant not found: {tid}")
    data = doc.to_dict() or {}
    email = _admin_user_email(data, tid)

    user = get_auth().get_user_by_email(email)
    password = generate_password()
    get_auth().update_user(user.uid, password=password)

    now = datetime.now(timezone.utc)
    get_db().collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).set(
        {"audit": {
            "created_by": (data.get("audit") or {}).get("created_by"),
            "created_at": (data.get("audit") or {}).get("created_at"),
            "last_modified_by": actor.get("email") or actor.get("uid"),
            "last_modified_at": now.isoformat(),
        }},
        merge=True,
    )
    production_seed._audit("TENANT_PASSWORD_RESET", actor, tid, f"Reset admin password for {email}")
    logger.info(f"Admin password reset for tenant {tid} by {actor.get('uid')}")
    return {"tenant_id": tid, "email": email, "password": password}


def send_welcome_email_for_tenant(tid: str, actor: Dict[str, Any]) -> Dict[str, Any]:
    """Set a fresh temporary password and email it to the tenant's admin."""
    doc = get_db().collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).get()
    if not doc.exists:
        raise ValueError(f"tenant not found: {tid}")
    data = doc.to_dict() or {}
    email = _admin_user_email(data, tid)

    user = get_auth().get_user_by_email(email)
    password = generate_password()
    get_auth().update_user(user.uid, password=password)

    contact = data.get("contact") or {}
    context = {
        "contact_name": contact.get("name") or "there",
        "tenant_name": data.get("name") or tid,
        "admin_email": email,
        "password": password,
        "login_url": settings.APP_LOGIN_URL,
        "support_email": settings.APP_SUPPORT_EMAIL,
    }
    result = send_welcome_email(email, context)

    now = datetime.now(timezone.utc)
    get_db().collection(settings.FIREBASE_COLLECTION_TENANTS).document(tid).set(
        {"audit": {
            "created_by": (data.get("audit") or {}).get("created_by"),
            "created_at": (data.get("audit") or {}).get("created_at"),
            "last_modified_by": actor.get("email") or actor.get("uid"),
            "last_modified_at": now.isoformat(),
        }},
        merge=True,
    )
    production_seed._audit(
        "TENANT_WELCOME_EMAIL", actor, tid,
        f"Welcome email to {email}: provider={result.get('provider')} sent={result.get('sent', False)}",
    )
    logger.info(f"Welcome email for tenant {tid} -> {email} ({result.get('provider')})")
    return {
        "tenant_id": tid,
        "admin_email": email,
        "password": password,
        "delivery": result,
    }
